### ISSUE TITLE
Quitar caida y bug Perro

### ISSUE THREAD

**Issue by tatosweb** [Shinkei/PhaserInit#24]

**Comment by tatosweb** [comment]
@Shinkei I already fix the player bounce falling, but I do not remember what is the dog issue? do you remember? :san_marino:

**Comment by Shinkei** [comment]
that the dog stay in a point after killing the player and start to go rapidly from one side to another

**Comment by tatosweb** [comment]
jummm damn dog, jeje got it! i'll check it out

**Comment by Shinkei** [comment]
Manito,mande el cambio de una a master sin crear el PR, no me di cuenta 🤕
